version: '3.1'

services:

  db:
    image: mariadb:10.9.4
    restart: always
    volumes:
      - ./mariadb-vol-hashed:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    container_name: mariadb-cont

  servlet-app:
    image: servlet-app:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    container_name: servlet-app-cont

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    container_name: adminer-cont